# Generated by Django 4.1.7 on 2023-03-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('price', models.PositiveIntegerField()),
                ('promo_price', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Order Confirm', 'Order Confirm'), ('Out of Delivery', 'Out of Delivery'), ('Delivery', 'Delivery')], max_length=20)),
            ],
        ),
    ]
